# Generated by Django 4.2.3 on 2023-07-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('max_subs', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_fisc', models.TextField(unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gym_address', models.TextField()),
                ('fields', models.ManyToManyField(to='courseApi.fitnessfield')),
            ],
        ),
        migrations.CreateModel(
            name='CourseScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.TextField(choices=[('Mon', 'Lunedì'), ('Tue', 'Martedì'), ('Wed', 'Mercoledì'), ('Thu', 'Giovedì'), ('Fri', 'Venerdì'), ('Sat', 'Sabato'), ('Sun', 'Domenica')])),
                ('start1', models.TimeField()),
                ('end1', models.TimeField()),
                ('start2', models.TimeField(blank=True)),
                ('end2', models.TimeField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApi.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courseApi.fitnessfield'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courseApi.instructor'),
        ),
    ]
