# Generated by Django 4.2.4 on 2023-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_subs', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Mon', 'Lunedì'), ('Tue', 'Martedì'), ('Wed', 'Mercoledì'), ('Thu', 'Giovedì'), ('Fri', 'Venerdì'), ('Sat', 'Sabato'), ('Sun', 'Domenica')], max_length=50)),
                ('start1', models.TimeField()),
                ('end1', models.TimeField()),
                ('start2', models.TimeField(blank=True, null=True)),
                ('end2', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
