# Generated by Django 4.2.3 on 2023-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coursescheduleday',
            name='week_day',
            field=models.CharField(choices=[('Mon', 'Lunedì'), ('Tue', 'Martedì'), ('Wed', 'Mercoledì'), ('Thu', 'Giovedì'), ('Fri', 'Venerdì'), ('Sat', 'Sabato'), ('Sun', 'Domenica')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessfield',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='cod_fisc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='gym_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='coursescheduleday',
            unique_together={('course', 'week_day')},
        ),
    ]
